stages:
  - build
  - linters
  - unit-tests
  - deploy

BUILD:
  stage: build
  tags:
    - firstrunner
  script:
    - bash src/build.sh
  after_script:
    - bash src/tg.sh
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 day

CODESTYLE:
    stage: linters
    tags:
      - firstrunner
    script:
      - bash src/linters.sh
    after_script:
      - bash src/tg.sh

TEST:
    stage: unit-tests
    tags:
      - firstrunner
    script:
      - bash src/test.sh
    after_script:
      - bash src/tg.sh

DEPLOY:
    stage: deploy
    tags:
      - firstrunner
    script:
      - bash src/deploy.sh
      - echo 'deploy'
    after_script:
      - bash src/tg.sh
    when: manual  