version: "3"

services:
  myserver:
    image: myserver:v1
    build: part5_image/.
    volumes:
      - ./part5_image/nginx:/etc/nginx
  proxy-nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
    - ./nginx:/etc/nginx  
    depends_on:
      - myserver